Repository dnd-side-project/dnd-10th-4-frontend, pull requests merged in 2024-04, with the labels that each got.

#266 🔨 refactor: 폴라로이드 컴포넌트 수정
  src/components/ImageUploadButton/index.tsx
  src/components/Polaroid/index.stories.tsx
  src/components/Polaroid/index.tsx
  src/components/Polaroid/styles.ts
  src/components/PolaroidModal/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyImage.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterStoragePage/ReplyStorage/ReplyLetterModal.tsx
  src/pages/LetterStoragePage/SentStorage/SentLetterModal.tsx
  src/pages/LetterWritePage/components/LetterPaper/PolaroidImage.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
Labels: 🔨 Refactor

#267 ✨ feat: 보관함 페이지 새로운 UI 적용 - 폴라로이드 컴포넌트 수정 revert
  src/assets/images/bottleStorage.png
  src/assets/storageDrawer.png
  src/components/ImageUploadButton/index.tsx
  src/components/Polaroid/index.stories.tsx
  src/components/Polaroid/index.tsx
  src/components/Polaroid/styles.ts
  src/components/PolaroidModal/index.tsx
  src/constants/letterStorage.ts
  src/mocks/datas/storage.ts
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyImage.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/index.test.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterStoragePage/ReplyStorage/ReplyLetterModal.tsx
  src/pages/LetterStoragePage/ReplyStorage/index.tsx
  src/pages/LetterStoragePage/SentStorage/SentLetterModal.tsx
  src/pages/LetterStoragePage/SentStorage/index.tsx
  src/pages/LetterStoragePage/components/DeleteBottomSheet.tsx
  src/pages/LetterStoragePage/components/LetterModalHeader.tsx
  src/pages/LetterStoragePage/components/StorageContent.tsx
  src/pages/LetterStoragePage/components/StorageLetter.tsx
  src/pages/LetterStoragePage/components/StorageSendLetter.tsx
  src/pages/LetterStoragePage/hooks/useLetterReply.ts
  src/pages/LetterStoragePage/hooks/useLetterSent.ts
  src/pages/LetterStoragePage/index.tsx
  src/pages/LetterWritePage/components/LetterPaper/PolaroidImage.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
Labels: ✨ Feature

#268 🔨 refactor: 폴라로이드 컴포넌트 수정
  src/components/ImageUploadButton/index.tsx
  src/components/Polaroid/index.stories.tsx
  src/components/Polaroid/index.tsx
  src/components/Polaroid/styles.ts
  src/components/PolaroidModal/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyImage.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterStoragePage/ReplyStorage/ReplyLetterModal.tsx
  src/pages/LetterStoragePage/SentStorage/SentLetterModal.tsx
  src/pages/LetterWritePage/components/LetterPaper/PolaroidImage.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
Labels: 🔨 Refactor

#271 🚑 fix: 관리자 페이지 응답 데이터 비어있는 오류 수정
  src/pages/AdminMainPage/hooks/usePagedReportQuery.ts
  src/pages/AdminMainPage/hooks/usePagedUserQuery.ts
Labels: 🚑 Hotfix

#275 ✨ feat: 메타태그 오픈그래프 추가
  index.html
  src/assets/openGraph.png
Labels: ✨ Feature

#272 ✨ feat: 사용자 약관 동의 기능 작성
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/pages/OnboardingPage/hooks/useOnboardingForm.ts
  src/pages/OnboardingPage/steps/FirstStep.tsx
  src/pages/OnboardingPage/steps/FirstStep/TermsBottomSheet.tsx
  src/pages/OnboardingPage/steps/FirstStep/index.tsx
Labels: ✨ Feature

#279 🚑 fix: openGraph 이미지 호스팅한 이미지로 변경
  index.html
Labels: 🚑 Hotfix

#282 📚 docs: readme 수정
  README.md
Labels: 📦️ Chore

#283 🔨 refactor: 오픈그래프 이미지 수정
  index.html
  src/assets/openGraph.png
  src/pages/LetterStoragePage/index.tsx
Labels: 🔨 Refactor

#284 ✨ feat: 관리자가 특정 회원에게 편지 작성하는 기능
  src/mocks/handlers/admin.ts
  src/mocks/resolvers/admin.ts
  src/pages/AdminMainPage/components/LetterWriterModal.tsx
  src/pages/AdminMainPage/tabs/UserTab.tsx
Labels: ✨ Feature

#286 ✨ feat: 답장 받은 편지 삭제하기
  src/api/letter/apis.ts
  src/assets/icons/Siren.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/siren.svg
  src/mocks/handlers/letter.ts
  src/mocks/resolvers/letter.ts
  src/pages/LetterReplyPage/components/DeleteBottomSheet.tsx
  src/pages/LetterReplyPage/components/ReplyHeader.tsx
Labels: ✨ Feature

#288 🚑 fix: letterTag가 null일 경우를 대비하여 편지 태그 파싱 로직 수정
  src/pages/LetterReceptionPage/NormalReception/hooks/useLetterWithTags.ts
Labels: 🚑 Hotfix

#292 🚑 fix: 폼 입력 시 자동 focus 되는 현상 제거
  src/pages/LetterReceptionPage/NormalReception/index.tsx
  src/pages/LetterWritePage/index.tsx
Labels: 🚑 Hotfix

#290 🔨 refactor: toast UI 수정
  src/AdminApp.tsx
  src/App.tsx
  src/api/queryClient.ts
  src/components/ReportBottomSheet/index.tsx
  src/pages/AdminMainPage/components/LetterWriterModal.tsx
  src/pages/LetterReceptionPage/NormalReception/ReceivedLetter/TossBottomSheet.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyBottomSheet.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyImage.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx
  src/pages/LetterReplyPage/components/DeleteBottomSheet.tsx
  src/pages/LetterReplyPage/components/StorageBottomSheet.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterStoragePage/components/DeleteBottomSheet.tsx
  src/pages/LetterStoragePage/components/LetterModalHeader.tsx
  src/pages/LetterWritePage/components/LetterPaper/PolaroidImage.tsx
  src/pages/LetterWritePage/components/LetterPaper/index.tsx
  src/pages/LetterWritePage/components/LetterWriteContainer.tsx
  src/pages/LetterWritePage/components/WriteBottomSheet.tsx
Labels: 🔨 Refactor

#296 🔨 refactor: 흘러온편지 페이지 UI 수정
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyButton.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/index.tsx
Labels: 🔨 Refactor

#301 ✨ feat: 카카오 인앱브라우저에서 외부 브라우저 열기
  src/main.tsx
Labels: ✨ Feature

#298 ✨ feat: 페이지 별 동적 타이틀 적용
  package-lock.json
  package.json
  public/favicon.svg
  src/App.tsx
  src/components/TitleMelmet/index.tsx
  src/constants/routerPaths.ts
  src/main.tsx
  src/utils/routeUtils.test.ts
  src/utils/routeUtils.ts
Labels: ✨ Feature

#305 🚑 fix: mock service worker가 등록되지 않던 문제 수정
  src/main.tsx
Labels: 🚑 Hotfix

#307 📦 chore: 폰트 preload 적용 및 robots.txt 추가
  index.html
  public/robots.txt
  src/main.css
Labels: 📦️ Chore

#313 🚑 fix: 관리자 페이지 타이틀 수정
  src/AdminApp.tsx
  src/App.tsx
  src/components/TitleHelmet/index.tsx
Labels: 🚑 Hotfix

#310 📦 chore: Google Tag Manager 대신 gtag 적용
  index.html
  src/types/gtag.d.ts
  src/utils/logEvent.ts
Labels: 📦️ Chore
