Repository dnd-side-project/dnd-10th-4-frontend, pull requests merged in 2024-02, with the labels that each got.

#54 📦 chore: msw 모킹 환경 구성 및 API 호출 예시 작성
  .env
  .storybook/preview.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/instance.ts
  src/api/queryClient.ts
  src/api/test/apis.ts
  src/api/test/queryOptions.ts
  src/components/EmotionTestButton/index.stories.tsx
  src/components/MSWTestCard/index.stories.tsx
  src/components/MSWTestCard/index.tsx
  src/constants/.empty
  src/constants/endpoint.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/test.ts
  src/types/test.ts
  src/utils/mswUtils.ts
Labels: 📦️ Chore

#59 ✨ feat: 카카오 로그인 페이지 작성
  .env
  .stylelintrc
  src/App.tsx
  src/api/oauth2/apis.ts
  src/components/KakaoLoginButton/index.tsx
  src/main.css
  src/mocks/handlers/index.ts
  src/mocks/handlers/oauth2.ts
  src/pages/.empty
  src/pages/OnboardingPage/index.tsx
  src/pages/SigninKakaoPage/index.tsx
  src/pages/SigninPage/index.tsx
  src/pages/SigninPage/styles.ts
  src/router.tsx
  src/styles/textStyles.ts
Labels: ✨ Feature

#60 ✨ feat: 편지쓰기 페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/background.png
  src/assets/ocean.jpeg
  src/components/IconButton/index.tsx
  src/components/Tooltip/index.stories.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/styles.ts
  src/hooks/useTimeout.ts
  src/pages/LetterWritePage/components/AgeSlider.tsx
  src/pages/LetterWritePage/components/ConcernSelect.tsx
  src/pages/LetterWritePage/components/GenderSelect.tsx
  src/pages/LetterWritePage/components/LetterPaper.tsx
  src/pages/LetterWritePage/components/LetterReceiverContainer.tsx
  src/pages/LetterWritePage/components/LetterReceiverSelect.tsx
  src/pages/LetterWritePage/components/LetterWriteBottom.tsx
  src/pages/LetterWritePage/components/LetterWriteContent.tsx
  src/pages/LetterWritePage/components/index.tsx
  src/pages/LetterWritePage/index.tsx
  src/pages/LetterWritePage/styles.ts
  src/router.tsx
Labels: ✨ Feature

#61 ✨ feat: 온보딩 페이지 스텝 기능 및 UI 퍼블리싱 작업
  package-lock.json
  package.json
  src/assets/icons/Female.tsx
  src/assets/icons/Male.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/female.svg
  src/assets/icons/raw/male.svg
  src/components/Chip/styles.ts
  src/components/Funnel/createFunnel.ts
  src/components/Funnel/index.mdx
  src/components/Funnel/index.stories.tsx
  src/components/Funnel/index.tsx
  src/components/MusicButton/index.stories.tsx
  src/components/MusicButton/index.tsx
  src/contexts/useFunnelContext.ts
  src/hooks/useFunnel.ts
  src/pages/OnboardingPage/components/NavHeader/index.stories.tsx
  src/pages/OnboardingPage/components/NavHeader/index.tsx
  src/pages/OnboardingPage/components/NavHeader/styles.ts
  src/pages/OnboardingPage/components/Progress/index.stories.tsx
  src/pages/OnboardingPage/components/Progress/index.tsx
  src/pages/OnboardingPage/components/Progress/styles.ts
  src/pages/OnboardingPage/components/StepTemplate.tsx
  src/pages/OnboardingPage/index.tsx
  src/pages/OnboardingPage/steps/FirstStep.tsx
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/InputNicknameStep.tsx
  src/pages/OnboardingPage/steps/InputWorryStep.tsx
  src/pages/OnboardingPage/steps/IntroduceStep.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
  src/pages/OnboardingPage/steps/ShowNicknameStep.tsx
  src/pages/OnboardingPage/styles.ts
  src/pages/SigninPage/index.tsx
Labels: ✨ Feature

#62 ✨ feat: 편지쓰기 페이지 form 구현
  src/assets/icons/Close.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/close.svg
  src/components/LetterCard/styles.ts
  src/components/Polaroid/index.stories.tsx
  src/components/Polaroid/index.tsx
  src/components/Polaroid/styles.ts
  src/constants/schemaLiteral.ts
  src/pages/LetterWritePage/components/AgeSlider.tsx
  src/pages/LetterWritePage/components/ConcernSelect.tsx
  src/pages/LetterWritePage/components/GenderSelect.tsx
  src/pages/LetterWritePage/components/LetterPaper.tsx
  src/pages/LetterWritePage/components/LetterReceiverBottomSheet.tsx
  src/pages/LetterWritePage/components/LetterReceiverContainer.tsx
  src/pages/LetterWritePage/components/LetterReceiverSelect.tsx
  src/pages/LetterWritePage/components/LetterWriteBottom.tsx
  src/pages/LetterWritePage/components/LetterWriteContent.tsx
  src/pages/LetterWritePage/components/PolaroidImage.tsx
  src/pages/LetterWritePage/components/index.ts
  src/pages/LetterWritePage/components/index.tsx
  src/pages/LetterWritePage/components/inputs/AgeSlider.tsx
  src/pages/LetterWritePage/components/inputs/ConcernSelect.tsx
  src/pages/LetterWritePage/components/inputs/GenderSelect.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
  src/pages/LetterWritePage/components/inputs/LetterTextarea.tsx
  src/pages/LetterWritePage/index.tsx
  src/pages/LetterWritePage/styles.ts
Labels: ✨ Feature

#63 ✨ feat: 온보딩 페이지 사용자 인터랙션 로직 및 모킹 API 연동
  src/api/member/apis.ts
  src/api/member/queryOptions.ts
  src/components/GenderCard/index.stories.tsx
  src/components/GenderCard/index.tsx
  src/components/GenderCard/styles.ts
  src/components/LoadingSpinner/index.stories.tsx
  src/components/LoadingSpinner/index.tsx
  src/components/LoadingSpinner/styles.ts
  src/constants/colors.ts
  src/constants/users.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/member.ts
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/InputNicknameStep.tsx
  src/pages/OnboardingPage/steps/InputWorryStep.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
  src/pages/OnboardingPage/styles.ts
Labels: ✨ Feature

#64 ✨ feat: 로그인/온보딩 페이지 구현
  .env
  .stylelintrc
  package-lock.json
  package.json
  src/App.tsx
  src/api/member/apis.ts
  src/api/member/queryOptions.ts
  src/api/oauth2/apis.ts
  src/assets/icons/Female.tsx
  src/assets/icons/Male.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/female.svg
  src/assets/icons/raw/male.svg
  src/components/Chip/styles.ts
  src/components/Funnel/createFunnel.ts
  src/components/Funnel/index.mdx
  src/components/Funnel/index.stories.tsx
  src/components/Funnel/index.tsx
  src/components/GenderCard/index.stories.tsx
  src/components/GenderCard/index.tsx
  src/components/GenderCard/styles.ts
  src/components/KakaoLoginButton/index.tsx
  src/components/LoadingSpinner/index.stories.tsx
  src/components/LoadingSpinner/index.tsx
  src/components/LoadingSpinner/styles.ts
  src/components/MusicButton/index.stories.tsx
  src/components/MusicButton/index.tsx
  src/constants/colors.ts
  src/constants/users.ts
  src/contexts/useFunnelContext.ts
  src/hooks/useFunnel.ts
  src/main.css
  src/mocks/handlers/index.ts
  src/mocks/handlers/member.ts
  src/mocks/handlers/oauth2.ts
  src/pages/.empty
  src/pages/OnboardingPage/components/NavHeader/index.stories.tsx
  src/pages/OnboardingPage/components/NavHeader/index.tsx
  src/pages/OnboardingPage/components/NavHeader/styles.ts
  src/pages/OnboardingPage/components/Progress/index.stories.tsx
  src/pages/OnboardingPage/components/Progress/index.tsx
  src/pages/OnboardingPage/components/Progress/styles.ts
  src/pages/OnboardingPage/components/StepTemplate.tsx
  src/pages/OnboardingPage/index.tsx
  src/pages/OnboardingPage/steps/FirstStep.tsx
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/InputNicknameStep.tsx
  src/pages/OnboardingPage/steps/InputWorryStep.tsx
  src/pages/OnboardingPage/steps/IntroduceStep.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
  src/pages/OnboardingPage/steps/ShowNicknameStep.tsx
  src/pages/OnboardingPage/styles.ts
  src/pages/SigninKakaoPage/index.tsx
  src/pages/SigninPage/index.tsx
  src/pages/SigninPage/styles.ts
  src/router.tsx
  src/styles/textStyles.ts
Labels: ✨ Feature

#66 💄 design: Tabs 컴포넌트 새로운 디자인 반영 및 트랜지션 추가
  src/components/Tabs/styles.ts
Labels: ✨ Feature

#71 💄 design: 온보딩 페이지 디자인 변동 사항 반영
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/Chip/styles.ts
  src/components/GenderCard/styles.ts
  src/components/Header/index.stories.tsx
  src/components/Header/style.ts
  src/components/Navbar/index.stories.tsx
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/InputWorryStep.tsx
  src/pages/OnboardingPage/styles.ts
Labels: ✨ Feature

#69 ✨ feat: 로그인 인가 토큰 관련 로직 작성
  package-lock.json
  package.json
  src/api/auth/apis.ts
  src/api/instance.test.ts
  src/api/instance.ts
  src/api/member/apis.ts
  src/api/oauth2/apis.ts
  src/api/queryClient.ts
  src/api/test/apis.ts
  src/constants/errorMessages.ts
  src/constants/storageKeys.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/oauth2.ts
  src/mocks/node.ts
  src/pages/SigninKakaoPage/index.tsx
  src/setupTests.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#68 ✨ feat: 편지 쓰기 모킹 API 구현
  index.html
  src/api/letter/apis.ts
  src/api/letter/queryOptions.ts
  src/assets/icons/ImageSquare.tsx
  src/assets/icons/raw/imageSquare.svg
  src/components/Polaroid/styles.ts
  src/constants/letters.ts
  src/constants/schemaLiteral.ts
  src/constants/users.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterWritePage/components/LetterReceiverBottomSheet.tsx
  src/pages/LetterWritePage/components/LetterReceiverContainer.tsx
  src/pages/LetterWritePage/components/LetterWriteBottom.tsx
  src/pages/LetterWritePage/components/PolaroidImage.tsx
  src/pages/LetterWritePage/components/index.ts
  src/pages/LetterWritePage/components/inputs/AgeSlider.tsx
  src/pages/LetterWritePage/components/inputs/GenderSelect.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
  src/pages/LetterWritePage/components/inputs/WorrySelect.tsx
  src/pages/LetterWritePage/index.tsx
  src/pages/LetterWritePage/styles.ts
  src/types/letter.ts
Labels: ✨ Feature

#76 📦 chore: msw 경고 메시지 화이트리스트 처리
  .storybook/preview.tsx
  src/components/Audio/index.tsx
  src/constants/errorMessages.ts
  src/constants/msw.ts
  src/constants/queryStrings.ts
  src/main.tsx
  src/mocks/handlers/member.ts
  src/utils/mswUtils.ts
Labels: 📦️ Chore

#78 ✨ feat: LetterTextarea, ImageUploadButton 컴포넌트 작성
  src/components/ImageUploadButton/index.stories.tsx
  src/components/ImageUploadButton/index.tsx
  src/components/ImageUploadButton/styles.ts
  src/components/LetterTextarea/index.stories.tsx
  src/components/LetterTextarea/index.tsx
  src/components/LetterTextarea/styles.ts
  src/pages/LetterWritePage/components/LetterPaper.tsx
  src/pages/LetterWritePage/components/index.ts
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
  src/pages/LetterWritePage/components/inputs/LetterContent.tsx
  src/pages/LetterWritePage/components/inputs/LetterTextarea.tsx
  src/pages/LetterWritePage/index.tsx
Labels: ✨ Feature

#81 ✨ feat: 메인 페이지 레이아웃 구성
  package-lock.json
  package.json
  src/assets/images/bottle.png
  src/components/IconButton/index.stories.tsx
  src/components/IconButton/index.tsx
  src/components/IconButton/styles.ts
  src/components/MusicButton/index.tsx
  src/pages/MainPage/components/CarouselArea.tsx
  src/pages/MainPage/index.tsx
  src/pages/MainPage/styles.ts
  src/router.tsx
Labels: ✨ Feature

#83 ✨ feat: 흘러온 편지 페이지 UI 구현
  src/components/LetterAccordion/index.tsx
  src/components/LetterAccordion/styles.ts
  src/components/LetterCard/styles.ts
  src/pages/LetterReceptionPage/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/components/LetterContent.tsx
  src/pages/LetterReceptionPage/components/ReceptionHeader.tsx
  src/pages/LetterReceptionPage/components/ReceptionPolaroid.tsx
  src/pages/LetterReceptionPage/intex.tsx
  src/router.tsx
Labels: ✨ Feature

#89 ✨ feat: 메인 페이지의 TimeChip 시간 표현
  src/mocks/datas/letter.ts
  src/pages/MainPage/components/CarouselArea/index.tsx
  src/pages/MainPage/components/CarouselArea/styles.ts
  src/pages/MainPage/components/TimeChip/index.stories.tsx
  src/pages/MainPage/components/TimeChip/index.tsx
  src/pages/MainPage/components/TimeChip/styles.ts
  src/pages/OnboardingPage/components/NavHeader/index.stories.tsx
  src/pages/OnboardingPage/components/Progress/index.stories.tsx
  src/utils/dateUtils.test.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature

#94 🚑 fix: 배경 이미지 흰색 구분선 제거
  src/assets/background.png
  src/components/Background/styles.ts
Labels: 🚑 Hotfix

#96 🔨 refactor: 온보딩 페이지 상태관리 리팩토링
  src/components/GenderCard/index.stories.tsx
  src/components/GenderCard/index.tsx
  src/components/MusicButton/index.tsx
  src/pages/OnboardingPage/hooks/useOnboardingForm.ts
  src/pages/OnboardingPage/index.tsx
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/InputNicknameStep.tsx
  src/pages/OnboardingPage/steps/InputWorryStep.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
  src/pages/OnboardingPage/steps/ShowNicknameStep.tsx
  src/utils/arrayUtils.test.ts
  src/utils/arrayUtils.ts
  src/utils/stringUtils.test.ts
  src/utils/stringUtils.ts
Labels: 🔨 Refactor

#102 💄 design: 마이 페이지 UI 작업
  .github/workflows/preview.yml
  src/components/IconButton/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/components/BirthdayBottomSheet.tsx
  src/pages/MyPage/components/GenderBottomSheet.tsx
  src/pages/MyPage/components/NicknameBottomSheet.tsx
  src/pages/MyPage/components/WorryBottomSheet.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/router.tsx
Labels: ✨ Feature

#106 ✨ feat: 마이 페이지의 전반적인 API 호출 로직 구현
  src/api/member/apis.ts
  src/components/Chip/index.tsx
  src/components/Chip/styles.ts
  src/components/GenderCard/index.stories.tsx
  src/components/LoadingSpinner/index.tsx
  src/mocks/handlers/member.ts
  src/pages/MyPage/components/BirthdayBottomSheet.tsx
  src/pages/MyPage/components/GenderBottomSheet.tsx
  src/pages/MyPage/components/NicknameBottomSheet.tsx
  src/pages/MyPage/components/WorryBottomSheet.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/pages/OnboardingPage/hooks/useOnboardingForm.ts
  src/pages/SigninPage/index.tsx
Labels: ✨ Feature

#109 ✨ feat: 아직 안 읽은 편지에 반짝이 효과 추가
  src/api/letter/apis.ts
  src/assets/images/bottleReception1.png
  src/assets/images/bottleReception2.png
  src/assets/images/bottleReception3.png
  src/assets/images/bottleReception4.png
  src/assets/images/sparkleBig.png
  src/assets/images/sparkleSmall.png
  src/constants/storageKeys.ts
  src/pages/MainPage/components/CarouselArea/ReceptionBottle.tsx
  src/pages/MainPage/components/CarouselArea/ReplyBottle.tsx
  src/pages/MainPage/components/CarouselArea/bottleData.ts
  src/pages/MainPage/components/CarouselArea/index.tsx
  src/pages/MainPage/components/CarouselArea/styles.ts
  src/pages/MainPage/components/Sparkle/index.stories.ts
  src/pages/MainPage/components/Sparkle/index.tsx
  src/pages/MainPage/components/Sparkle/styles.ts
  src/pages/MainPage/hooks/useLetterSlides.ts
  src/router.tsx
  src/stores/useReadLetterStore.ts
  src/types/letter.ts
  src/utils/arrayUtils.test.ts
  src/utils/arrayUtils.ts
Labels: ✨ Feature, 🔨 Refactor

#111 💄 design: 온보딩 페이지 및 버튼, 탭 등 디자인 변동사항 반영
  src/assets/icons/Female.tsx
  src/assets/icons/Male.tsx
  src/components/Button/styles.ts
  src/components/Chip/styles.ts
  src/components/GenderCard/index.tsx
  src/components/GenderCard/styles.ts
  src/components/Tabs/styles.ts
  src/pages/OnboardingPage/components/StepTemplate.tsx
  src/pages/OnboardingPage/steps/FirstStep.tsx
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/InputNicknameStep.tsx
  src/pages/OnboardingPage/steps/InputWorryStep.tsx
  src/pages/OnboardingPage/steps/IntroduceStep.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
  src/pages/OnboardingPage/steps/ShowNicknameStep.tsx
  src/pages/SigninPage/index.tsx
  src/styles/textStyles.ts
Labels: ✨ Feature

#101 ✨ feat: 카카오 리다이렉션 이후 토큰 보관 로직 작성
  .env
  src/api/auth/apis.ts
  src/mocks/datas/letter.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/member.ts
  src/mocks/handlers/test.ts
  src/pages/SigninKakaoPage/index.tsx
  src/pages/SigninPage/index.tsx
  src/utils/mswUtils.ts
Labels: ✨ Feature

#117 📦 chore: 로그인 API 변경 적용
  src/api/auth/apis.ts
  src/mocks/handlers/auth.ts
Labels: 📦️ Chore

#115 📦 chore: Sentry 설정, ErrorBoundary 작성
  .env
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/App.tsx
  src/api/instance.test.ts
  src/api/instance.ts
  src/api/letter/apis.ts
  src/components/ErrorBoundary/ApiErrorBoundary.stories.tsx
  src/components/ErrorBoundary/ApiErrorBoundary.tsx
  src/components/ErrorBoundary/UnknownErrorBoundary.stories.tsx
  src/components/ErrorBoundary/UnknownErrorBoundary.tsx
  src/components/ErrorBoundary/fallback/ReceptionFallback.tsx
  src/components/ErrorBoundary/fallback/RootApiFallback.tsx
  src/components/ErrorBoundary/fallback/RootUnknownFallback.tsx
  src/components/ErrorBoundary/fallback/styles.ts
  src/main.tsx
  src/mocks/handlers/auth.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/index.tsx
  src/pages/LetterReceptionPage/intex.tsx
  src/router.tsx
  src/utils/mswUtils.ts
  vite.config.ts
Labels: ✨ Feature, 📦️ Chore

#122 🚑 fix: Preview 배포에서 로그인 되어있도록 설정
  src/api/letter/apis.ts
  src/api/letter/queryOptions.ts
  src/components/ErrorBoundary/fallback/RootApiFallback.tsx
  src/components/ErrorBoundary/fallback/RootUnknownFallback.tsx
  src/constants/errorMessages.ts
  src/main.tsx
  src/pages/MainPage/hooks/useLetterSlides.ts
Labels: 🚑 Hotfix

#119 ✨ feat: 폴라로이드 이미지 추가 및 삭제 구현
  src/assets/icons/AddImage.tsx
  src/assets/icons/TrashCan.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/addImage.svg
  src/assets/icons/raw/trashCan.svg
  src/components/ImageUploadButton/index.tsx
  src/components/Polaroid/index.stories.tsx
  src/components/Polaroid/index.tsx
  src/components/Polaroid/styles.ts
  src/constants/schemaLiteral.ts
  src/pages/LetterWritePage/components/LetterPaper.tsx
  src/pages/LetterWritePage/components/LetterWriteBottom.tsx
  src/pages/LetterWritePage/components/PolaroidImage.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
Labels: ✨ Feature

#124 ✨ feat: 온보딩 페이지 API 모킹 및 연동
  src/api/member/apis.ts
  src/constants/errorMessages.ts
  src/mocks/handlers/member.ts
  src/pages/OnboardingPage/index.tsx
  src/pages/OnboardingPage/steps/InputBirthdayStep.tsx
  src/pages/OnboardingPage/steps/InputGenderStep.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
Labels: ✨ Feature

#127 ✨ feat: TagList 컴포넌트 구현 및 Chip 컴포넌트 수정
  src/assets/icons/CaretDown.tsx
  src/components/Chip/index.stories.tsx
  src/components/Chip/index.tsx
  src/components/Chip/styles.ts
  src/components/LetterCard/styles.ts
  src/components/TagList/index.stories.tsx
  src/components/TagList/index.tsx
  src/components/TagList/styles.ts
  src/constants/colors.ts
  src/pages/LetterReceptionPage/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/components/ReceptionPolaroid.tsx
  src/pages/LetterReceptionPage/components/TagList.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterWritePage/components/LetterReceiverContainer.tsx
Labels: ✨ Feature

#134 🔨 refactor: 편지쓰기 formData 이미지 유무에 따른 처리 방식 수정
  src/api/letter/apis.ts
Labels: 🔨 Refactor

#133 📦 chore: react-toastify 설치
  package-lock.json
  package.json
  src/App.tsx
  src/constants/errorMessages.ts
  src/pages/OnboardingPage/steps/LastStep.tsx
Labels: ✨ Feature, 📦️ Chore

#126 ✨ feat: 마이 페이지 API 변동 사항 반영
  src/api/member/apis.ts
  src/mocks/handlers/member.ts
  src/pages/MyPage/components/NicknameBottomSheet.tsx
  src/pages/MyPage/index.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
Labels: ✨ Feature

#129 ✨ feat: 흘러온 편지, 내게 온 답장 DetailTimeChip 구현
  src/components/DetailTimeChip/index.stories.tsx
  src/components/DetailTimeChip/index.tsx
  src/components/DetailTimeChip/styles.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/components/ReceptionHeader.tsx
  src/pages/LetterReplyPage/components/ReplyHeader.tsx
  src/pages/LetterReplyPage/index.tsx
  src/utils/dateUtils.test.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature

#138 💄 design: BottomSheet 합성 컴포넌트 요소 추가
  src/components/BottomSheet/components/ButtonSection.tsx
  src/components/BottomSheet/components/Content.tsx
  src/components/BottomSheet/components/Description.tsx
  src/components/BottomSheet/components/Divider.tsx
  src/components/BottomSheet/components/Title.tsx
  src/components/BottomSheet/components/styles.ts
  src/components/BottomSheet/index.stories.tsx
  src/components/BottomSheet/index.tsx
  src/styles/textStyles.ts
Labels: ✨ Feature

#136 🔨 refactor: msw 모킹 정리 및 withAuth 미들웨어 작성
  src/api/member/apis.ts
  src/constants/queryStrings.ts
  src/mocks/handlers/letter.ts
  src/mocks/handlers/member.ts
  src/mocks/middlewares/withAuth.ts
  src/pages/MyPage/index.tsx
  src/utils/mswUtils.ts
Labels: 🔨 Refactor

#141 💄 design: 마이 페이지 바텀 시트 디자인 변동사항 반영
  src/api/member/apis.ts
  src/components/Button/styles.ts
  src/components/DetailTimeChip/styles.ts
  src/constants/colors.ts
  src/mocks/handlers/member.ts
  src/pages/MainPage/components/TimeChip/index.tsx
  src/pages/MyPage/components/BirthdayBottomSheet.tsx
  src/pages/MyPage/components/GenderBottomSheet.tsx
  src/pages/MyPage/components/NicknameBottomSheet.tsx
  src/pages/MyPage/components/ResignBottomSheet.tsx
  src/pages/MyPage/components/SignoutBottomSheet.tsx
  src/pages/MyPage/components/WorryBottomSheet.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
Labels: ✨ Feature

#139 ✨ feat: 흘러온 편지 페이지 API 변동 사항 반영
  src/api/letter/apis.ts
  src/components/ErrorBoundary/fallback/ReceptionFallback.tsx
  src/constants/errorMessages.ts
  src/mocks/datas/letter.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/components/ReceptionPolaroid.tsx
  src/pages/LetterReceptionPage/hooks/useLetterWithTags.ts
  src/types/letter.ts
Labels: ✨ Feature

#146 🚑 fix: 최초 로그인이 아니면 메인 페이지로 이동하도록 수정
  src/pages/SigninKakaoPage/index.tsx
Labels: 🚑 Hotfix

#149 🚑 fix: Chromatic 배포 이슈 해결
  src/constants/msw.ts
  src/main.tsx
Labels: 🚑 Hotfix

#153 🚑 fix: Sentry Environment 롤백
  src/constants/msw.ts
  src/main.tsx
Labels: 🚑 Hotfix

#150 ✨ feat: 내게 온 답장 페이지 API 변동 사항 반영
  src/api/letter/apis.ts
  src/components/ErrorBoundary/fallback/LetterAccessFallback.tsx
  src/constants/errorMessages.ts
  src/mocks/datas/letter.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/hooks/useLetterWithTags.ts
  src/pages/LetterReceptionPage/index.tsx
  src/pages/LetterReceptionPage/styles.ts
  src/pages/LetterReplyPage/components/BottomButton.tsx
  src/pages/LetterReplyPage/hooks/useLetterReplyWithTag.ts
  src/pages/LetterReplyPage/index.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterReplyPage/styles.ts
  src/types/letter.ts
Labels: ✨ Feature

#156 💄 design: PaginationBar 컴포넌트 작성
  src/components/PaginationBar/index.stories.tsx
  src/components/PaginationBar/index.tsx
  src/components/PaginationBar/style.ts
Labels: ✨ Feature

#157 ✨ feat: Dropdown 컴포넌트 구현
  src/assets/icons/Copy.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/copy.svg
  src/components/Dropdown/index.stories.tsx
  src/components/Dropdown/index.tsx
  src/components/Dropdown/styles.ts
Labels: ✨ Feature

#160 ✨ feat: 메인 페이지 편지지 갯수 적용
  .storybook/preview.tsx
  src/api/member/apis.ts
  src/api/queryClient.ts
  src/components/MusicButton/index.tsx
  src/mocks/handlers/member.ts
  src/pages/MainPage/components/WritingBottomButton/index.tsx
  src/pages/MainPage/components/WritingButton/index.stories.tsx
  src/pages/MainPage/components/WritingButton/index.tsx
  src/pages/MainPage/components/WritingButton/style.ts
  src/pages/MainPage/index.tsx
  src/pages/MainPage/styles.ts
  src/pages/MyPage/index.tsx
Labels: ✨ Feature

#162 ✨ feat: 편지 쓰기 페이지 API 변동 사항 반영
  src/constants/errorMessages.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterWritePage/components/LetterPaper.tsx
  src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
  src/pages/LetterWritePage/index.tsx
Labels: ✨ Feature

#165 ✨ feat: Tooltip 컴포넌트에 mountKey 추가
  src/components/Tooltip/index.stories.tsx
  src/components/Tooltip/index.tsx
  src/pages/MainPage/components/WritingButton/index.tsx
Labels: ✨ Feature

#167 🔨 refactor: ageStart 필드를 ageRangeStart 로 변경
  src/mocks/datas/letter.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/hooks/useLetterWithTags.ts
  src/pages/LetterReplyPage/hooks/useLetterReplyWithTag.ts
  src/types/letter.ts
Labels: 🔨 Refactor

#168 ✨ feat: 온보딩 편지 UI 및 툴팁 작업
  src/assets/images/onboardingLetterImage.jpg
  src/pages/LetterReceptionOnboardingPage/components/PolaroidModal/index.tsx
  src/pages/LetterReceptionOnboardingPage/components/PolaroidModal/style.ts
  src/pages/LetterReceptionOnboardingPage/index.tsx
  src/pages/LetterReceptionOnboardingPage/styles.ts
  src/pages/MainPage/components/CarouselArea/bottleData.ts
  src/pages/MainPage/components/WritingBottomButton/index.tsx
  src/pages/MainPage/index.tsx
  src/router.tsx
Labels: ✨ Feature

#171 ✨ feat: 흘러온 편지 페이지 답장 이미지 첨부 기능 구현
  src/api/letter/apis.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/styles.ts
Labels: ✨ Feature

#169 ✨ feat: 보관함 페이지 UI 구현
  src/App.tsx
  src/assets/icons/ScrolLetter.tsx
  src/assets/icons/index.ts
  src/assets/icons/raw/scrolLetter.svg
  src/components/Background/index.tsx
  src/components/Background/styles.ts
  src/components/Dropdown/index.tsx
  src/components/LetterAccordion/index.tsx
  src/components/LetterAccordion/styles.ts
  src/components/LetterCard/styles.ts
  src/components/Modal/styles.ts
  src/components/PaginationBar/style.ts
  src/components/Tabs/styles.ts
  src/pages/LetterReceptionPage/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/components/LetterContent.tsx
  src/pages/LetterReceptionPage/components/ReceptionPolaroid.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterStoragePage/archiveLetters/index.tsx
  src/pages/LetterStoragePage/components/StorageContent.tsx
  src/pages/LetterStoragePage/components/StorageEmpty.tsx
  src/pages/LetterStoragePage/components/StorageHeader.tsx
  src/pages/LetterStoragePage/components/StorageLetter.tsx
  src/pages/LetterStoragePage/index.tsx
  src/pages/LetterStoragePage/mySentLetters/index.tsx
  src/pages/LetterStoragePage/testData.ts
  src/router.tsx
Labels: ✨ Feature

#183 🔨 refactor: Reception 타입 imagePath 필드를 sendImagePath 로 변경
  src/mocks/datas/letter.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/types/letter.ts
Labels: 🔨 Refactor

#185 💄 design: 메인 페이지 디자인 변동사항 반영
  src/assets/images/bottleReply1.png
  src/assets/images/bottleReply2.png
  src/components/BottomSheet/components/Description.tsx
  src/pages/MainPage/components/CarouselArea/ReplyBottle.tsx
  src/pages/MainPage/components/CarouselArea/index.tsx
  src/pages/MainPage/components/LetterCountIconButton/LetterCountBottomSheet.tsx
  src/pages/MainPage/components/LetterCountIconButton/index.stories.tsx
  src/pages/MainPage/components/LetterCountIconButton/index.tsx
  src/pages/MainPage/components/LetterCountIconButton/style.ts
  src/pages/MainPage/components/WritingButton/index.tsx
  src/pages/MainPage/index.tsx
Labels: ✨ Feature

#187 ✨ feat: 마이 페이지 생년월일 버그 수정 및 토스트 추가
  src/mocks/handlers/member.ts
  src/pages/MyPage/components/BirthdayBottomSheet.tsx
  src/pages/MyPage/components/GenderBottomSheet.tsx
  src/pages/MyPage/components/NicknameBottomSheet.tsx
  src/pages/MyPage/components/ResignBottomSheet.tsx
  src/pages/MyPage/components/WorryBottomSheet.tsx
  src/pages/MyPage/index.tsx
  src/pages/OnboardingPage/steps/LastStep.tsx
Labels: ✨ Feature

#177 ✨ feat: 온보딩 편지 API 연동
  src/api/letter/apis.ts
  src/assets/images/onboardingLetterImage.jpg
  src/components/Tooltip/index.tsx
  src/mocks/datas/letter.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/NormalReception/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReceivedLetter/styles.ts
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReceivedAccordionLetter.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/styles.ts
  src/pages/LetterReceptionPage/NormalReception/components/LetterContent.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionHeader.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx
  src/pages/LetterReceptionPage/NormalReception/hooks/useLetterWithTags.ts
  src/pages/LetterReceptionPage/NormalReception/index.tsx
  src/pages/LetterReceptionPage/NormalReception/styles.ts
  src/pages/LetterReceptionPage/OnboardingReception/components/PolaroidModal/index.tsx
  src/pages/LetterReceptionPage/OnboardingReception/components/PolaroidModal/style.ts
  src/pages/LetterReceptionPage/OnboardingReception/index.tsx
  src/pages/LetterReceptionPage/OnboardingReception/styles.ts
  src/pages/LetterReceptionPage/index.tsx
  src/pages/LetterReceptionPage/styles.ts
  src/pages/MainPage/components/CarouselArea/ReceptionBottle.tsx
  src/pages/MainPage/components/CarouselArea/index.tsx
  src/pages/MainPage/components/WritingBottomButton/index.tsx
  src/pages/MainPage/index.tsx
  src/router.tsx
  src/types/letter.ts
Labels: ✨ Feature, 🔨 Refactor

#191 ✨ feat: 흘려온편지 페이지 바텀시트, 토스트 구현
  src/api/letter/apis.ts
  src/pages/LetterReceptionPage/NormalReception/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyButton.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyImage.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx
  src/pages/LetterReceptionPage/NormalReception/index.tsx
  src/pages/LetterReceptionPage/index.tsx
Labels: ✨ Feature

#192 ✨ feat: AuthLayout, LoadingScreen, NotFoundPage 작성
  src/components/ErrorBoundary/fallback/RootUnknownFallback.tsx
  src/components/LoadingScreen/index.stories.tsx
  src/components/LoadingScreen/index.tsx
  src/components/LoadingScreen/styles.ts
  src/constants/routerPaths.ts
  src/layouts/AuthLayout.tsx
  src/pages/LetterReceptionPage/NormalReception/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/index.tsx
  src/pages/LetterReceptionPage/NormalReception/index.tsx
  src/pages/LetterReceptionPage/OnboardingReception/index.tsx
  src/pages/LetterReplyPage/components/BottomButton.tsx
  src/pages/LetterReplyPage/components/ReplyHeader.tsx
  src/pages/LetterStoragePage/archiveLetters/index.tsx
  src/pages/LetterStoragePage/components/StorageHeader.tsx
  src/pages/LetterStoragePage/mySentLetters/index.tsx
  src/pages/LetterWritePage/index.tsx
  src/pages/MainPage/components/CarouselArea/ReceptionBottle.tsx
  src/pages/MainPage/components/CarouselArea/ReplyBottle.tsx
  src/pages/MainPage/components/WritingBottomButton/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/ModalTestPage/index.tsx
  src/pages/ModalTestPage/styles.ts
  src/pages/MyPage/components/ResignBottomSheet.tsx
  src/pages/MyPage/components/SignoutBottomSheet.tsx
  src/pages/MyPage/index.tsx
  src/pages/NotFoundPage/index.stories.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/NotFoundPage/style.ts
  src/pages/OnboardingPage/steps/LastStep.tsx
  src/pages/SigninKakaoPage/index.tsx
  src/pages/SigninPage/index.tsx
  src/router.tsx
  src/types/.empty
Labels: ✨ Feature, 🔨 Refactor

#195 🚑 fix: Send 타입의 postList 필드를 letters로 변경
  src/mocks/datas/send.ts
  src/pages/LetterStoragePage/mySentLetters/index.tsx
  src/types/letter.ts
Labels: 🚑 Hotfix

#199 🚑 fix: 발표 전 피드백 내용 반영
  src/components/ErrorBoundary/fallback/RootApiFallback.tsx
  src/components/ErrorBoundary/fallback/RootUnknownFallback.tsx
  src/pages/LetterReceptionPage/OnboardingReception/index.tsx
  src/pages/LetterWritePage/index.tsx
  src/pages/MainPage/hooks/useLetterSlides.ts
  src/pages/OnboardingPage/steps/LastStep.tsx
Labels: 🚑 Hotfix

#202 ✨ feat: 고민 초기화 기능 작성
  src/api/letter/apis.ts
  src/mocks/handlers/letter.ts
  src/pages/LetterReceptionPage/OnboardingReception/index.tsx
  src/pages/MyPage/components/WorryBottomSheet.tsx
Labels: ✨ Feature

#201 ✨ feat: 편지 보관함 페이지 UI 토스트 및 바텀시트 적용
  src/components/Dropdown/styles.ts
  src/pages/LetterStoragePage/components/DeleteBottomSheet.tsx
  src/pages/LetterStoragePage/components/StorageLetter.tsx
  src/pages/LetterStoragePage/components/StorageSendLetter.tsx
Labels: ✨ Feature

#206 🚑 fix: 온보딩 편지에 대한 임시 예외 처리 로직 작성
  src/pages/LetterStoragePage/components/StorageLetter.tsx
Labels: 🚑 Hotfix

#208 🚑 fix: 온보딩 편지 햄버거 아이콘 위치 수정
  src/pages/LetterStoragePage/components/StorageLetter.tsx
Labels: 🚑 Hotfix

#212 🚑 fix: 편지 보관시 메인 페이지로 이동
  src/pages/LetterReplyPage/components/BottomButton.tsx
Labels: 🚑 Hotfix

#216 📚 docs: readme 수정
  README.md
Labels: 📚 Docs

#218 🔨 refactor: Github Actions 워크플로 리팩토링
  .github/actions/install/action.yml
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: 🔨 Refactor, 📦️ Chore

#220 🔨 refactor: Header 컴포넌트를 합성 컴포넌트로 리팩토링
  src/components/Header/components/Center.tsx
  src/components/Header/components/Left.tsx
  src/components/Header/components/Right.tsx
  src/components/Header/components/style.ts
  src/components/Header/index.stories.tsx
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/PolaroidModal/index.tsx
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionHeader.tsx
  src/pages/LetterReceptionPage/OnboardingReception/components/PolaroidModal/index.tsx
  src/pages/LetterReceptionPage/OnboardingReception/index.tsx
  src/pages/LetterReplyPage/components/ReplyHeader.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
  src/pages/LetterStoragePage/components/StorageHeader.tsx
  src/pages/LetterWritePage/components/LetterWriteHeader.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/OnboardingPage/components/NavHeader/index.tsx
  src/pages/OnboardingPage/index.tsx
  src/pages/SigninPage/index.tsx
Labels: 🔨 Refactor
