Repository dnd-side-project/dnd-10th-4-frontend, pull requests merged in 2024-03, with the labels that each got.

#223 📦 chore: testing-library 설정
  .eslintrc
  __mocks__/zustand.ts
  package-lock.json
  package.json
  src/api/member/apis.ts
  src/constants/routerPaths.ts
  src/mocks/datas/member.ts
  src/mocks/handlers/member.ts
  src/mocks/resolvers/member.ts
  src/pages/MyPage/components/NicknameBottomSheet.test.tsx
  src/pages/MyPage/components/NicknameBottomSheet.tsx
  src/setupTests.ts
  src/types/member.ts
  src/utils/testing-library.tsx
Labels: 🔨 Refactor, 📦️ Chore

#225 🔨 refactor: 전역 MutationOption에 에러 핸들링 콜백 적용
  src/api/queryClient.ts
  src/pages/LetterWritePage/index.tsx
  src/pages/MyPage/components/NicknameBottomSheet.tsx
Labels: 🔨 Refactor

#227 🔨 refactor: auth, letter 관련 API Path 및 msw resolver 정리
  README.md
  src/api/auth/apis.ts
  src/api/letter/apis.ts
  src/constants/routerPaths.ts
  src/mocks/datas/letter.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/letter.ts
  src/mocks/handlers/member.ts
  src/mocks/resolvers/auth.ts
  src/mocks/resolvers/letter.ts
  src/mocks/resolvers/member.ts
  src/utils/mswUtils.ts
Labels: 🔨 Refactor

#229 🔨 refactor: 마이 페이지 테스트 코드 작성
  src/api/instance.test.ts
  src/api/queryClient.ts
  src/mocks/datas/member.ts
  src/pages/MyPage/components/BirthdayBottomSheet.test.tsx
  src/pages/MyPage/components/BirthdayBottomSheet.tsx
  src/pages/MyPage/components/GenderBottomSheet.test.tsx
  src/pages/MyPage/components/GenderBottomSheet.tsx
  src/pages/MyPage/components/LogoutBottomSheet.test.tsx
  src/pages/MyPage/components/LogoutBottomSheet.tsx
  src/pages/MyPage/components/NicknameBottomSheet.test.tsx
  src/pages/MyPage/components/ResignBottomSheet.test.tsx
  src/pages/MyPage/components/ResignBottomSheet.tsx
  src/pages/MyPage/components/WorryBottomSheet.tsx
  src/pages/MyPage/index.test.tsx
  src/pages/MyPage/index.tsx
  src/types/utility.ts
  src/utils/testing-library.tsx
Labels: 🔨 Refactor

#231 🔨 refactor: 내게 온 답장 페이지 테스트 코드 작성
  src/pages/LetterReplyPage/components/BottomButton.test.tsx
  src/pages/LetterReplyPage/components/BottomButton.tsx
  src/pages/LetterReplyPage/components/StorageBottomSheet.test.tsx
  src/pages/LetterReplyPage/components/StorageBottomSheet.tsx
  src/pages/LetterReplyPage/hooks/useLetterReplyWithTag.ts
  src/pages/LetterReplyPage/replyLetter/index.test.tsx
  src/pages/LetterReplyPage/replyLetter/index.tsx
  src/pages/LetterReplyPage/sentLetter/index.test.tsx
  src/pages/LetterReplyPage/sentLetter/index.tsx
Labels: 🔨 Refactor

#235 📦 chore: 백엔드 API 엔드포인트 변경
  .env
Labels: 📦️ Chore

#236 📦 chore: Google Analytics 설정
  README.md
  index.html
Labels: 📦️ Chore

#241 🔨 refactor: 물병 위치 기억을 위해 useLetterSlideStore 작성
  README.md
  src/constants/letters.ts
  src/constants/storageKeys.ts
  src/pages/MainPage/components/CarouselArea/ReceptionBottle.tsx
  src/pages/MainPage/components/CarouselArea/ReplyBottle.tsx
  src/pages/MainPage/components/CarouselArea/index.tsx
  src/pages/MainPage/hooks/useLetterSlides.ts
  src/router.tsx
  src/stores/useLetterSlideStore.test.ts
  src/stores/useLetterSlideStore.ts
  src/stores/useReadLetterStore.ts
Labels: ✨ Feature, 🔨 Refactor

#244 🔨 refactor: Tooltip을 합성 컴포넌트로 리팩토링
  src/components/MusicButton/index.tsx
  src/components/Polaroid/index.tsx
  src/components/Tooltip/components/Content.stories.tsx
  src/components/Tooltip/components/Content.tsx
  src/components/Tooltip/components/Trigger.stories.tsx
  src/components/Tooltip/components/Trigger.tsx
  src/components/Tooltip/contexts/TooltipContext.ts
  src/components/Tooltip/index.stories.tsx
  src/components/Tooltip/index.tsx
  src/pages/LetterReceptionPage/NormalReception/ReceivedLetter/index.tsx
  src/pages/LetterReceptionPage/OnboardingReception/index.tsx
  src/pages/LetterReplyPage/components/BottomButton.tsx
  src/pages/LetterReplyPage/components/ReplyHeader.tsx
  src/pages/LetterWritePage/components/LetterReceiverContainer.tsx
  src/pages/MainPage/components/CarouselArea/ReceptionBottle.tsx
  src/pages/MainPage/components/CarouselArea/ReplyBottle.tsx
  src/pages/MainPage/components/LetterCountIconButton/index.tsx
  src/pages/MainPage/components/WritingBottomButton/index.tsx
  src/pages/MainPage/index.tsx
Labels: 🔨 Refactor

#246 📦 chore: Storybook 8 마이그레이션
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/Tooltip/index.stories.tsx
Labels: 📦️ Chore

#247 🔨 refactor: 편지 쓰기 페이지 테스트 코드 작성 및 컴포넌트 리팩토링
  src/components/Chip/index.tsx
  src/pages/LetterWritePage/components/BackwardBottomSheet.tsx
  src/pages/LetterWritePage/components/LetterPaper/LetterReceiverBottomSheet.test.tsx
  src/pages/LetterWritePage/components/LetterPaper/LetterReceiverBottomSheet.tsx
  src/pages/LetterWritePage/components/LetterPaper/LetterReceiverContainer.test.tsx
  src/pages/LetterWritePage/components/LetterPaper/LetterReceiverContainer.tsx
  src/pages/LetterWritePage/components/LetterPaper/PolaroidImage.tsx
  src/pages/LetterWritePage/components/LetterPaper/index.test.tsx
  src/pages/LetterWritePage/components/LetterPaper/index.tsx
  src/pages/LetterWritePage/components/LetterWriteBottom.tsx
  src/pages/LetterWritePage/components/LetterWriteContainer.test.tsx
  src/pages/LetterWritePage/components/LetterWriteContainer.tsx
  src/pages/LetterWritePage/components/LetterWriteContent.tsx
  src/pages/LetterWritePage/components/LetterWriteHeader.tsx
  src/pages/LetterWritePage/components/WriteBottomSheet.test.tsx
  src/pages/LetterWritePage/components/WriteBottomSheet.tsx
  src/pages/LetterWritePage/components/index.ts
  src/pages/LetterWritePage/index.tsx
Labels: 🔨 Refactor

#249 🔨 refactor: Background 레이아웃 수정
  src/App.tsx
  src/components/Background/index.tsx
  src/components/Background/styles.ts
  src/mocks/datas/letter.ts
  src/mocks/datas/storage.ts
  src/pages/LetterReceptionPage/NormalReception/styles.ts
  src/pages/LetterReceptionPage/OnboardingReception/styles.ts
  src/pages/LetterReplyPage/styles.ts
  src/pages/LetterStoragePage/index.tsx
  src/pages/LetterWritePage/styles.ts
  src/pages/MainPage/styles.ts
  src/pages/MyPage/style.ts
  src/pages/NotFoundPage/style.ts
  src/pages/SigninPage/styles.ts
Labels: 🔨 Refactor

#251 ✨ feat: 신고하기 바텀시트 UI 구현
  src/components/ReportBottomSheet/components/Radio.tsx
  src/components/ReportBottomSheet/components/styles.ts
  src/components/ReportBottomSheet/index.stories.tsx
  src/components/ReportBottomSheet/index.tsx
  src/components/ReportBottomSheet/styles.ts
  src/pages/LetterReceptionPage/NormalReception/components/ReceptionHeader.tsx
  src/pages/LetterReplyPage/components/ReplyHeader.tsx
Labels: ✨ Feature

#255 ✨ feat: 금칙어 필터링 기능 구현
  src/api/letter/apis.ts
  src/constants/filteringWords.ts
  src/utils/stringFilter.test.ts
  src/utils/stringFilter.ts
Labels: ✨ Feature

#261 ✨ feat: 관리자 페이지 작성
  package-lock.json
  package.json
  src/AdminApp.tsx
  src/App.tsx
  src/api/admin/apis.ts
  src/api/admin/queryOptions.ts
  src/components/Background/index.tsx
  src/components/Background/styles.ts
  src/components/PaginationBar/index.tsx
  src/components/Tabs/index.tsx
  src/constants/routerPaths.ts
  src/constants/users.ts
  src/layouts/AdminLayout.tsx
  src/mocks/datas/member.ts
  src/mocks/handlers/admin.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/member.ts
  src/mocks/resolvers/admin.ts
  src/mocks/resolvers/member.ts
  src/pages/AdminMainPage/components/UserExpelBottomSheet.tsx
  src/pages/AdminMainPage/hooks/usePagedReportQuery.ts
  src/pages/AdminMainPage/hooks/usePagedUserQuery.ts
  src/pages/AdminMainPage/index.tsx
  src/pages/AdminMainPage/style.ts
  src/pages/AdminMainPage/tabs/ReportTab.tsx
  src/pages/AdminMainPage/tabs/UserTab.tsx
  src/pages/SigninKakaoPage/index.tsx
  src/router.tsx
  src/stores/useAdminPageStore.ts
  src/types/admin.ts
  src/types/letter.ts
  src/types/pagination.ts
  src/utils/timerUtils.ts
Labels: ✨ Feature, 🔨 Refactor
